const fs = require('fs');
const path = 'C:/Users/Tanner/KiloProjects/trendsetter/api-explorer/data/apis.json';
const data = JSON.parse(fs.readFileSync(path, 'utf8'));
const existingNames = new Set(data.map(a => a.name));

const newEntries = [
  {name:'Stripe Treasury',category:'finance',description:'Banking-as-a-service API for embedding financial accounts, balances, and payment operations.',auth:'Bearer Token',rate_limit:'100 req/sec',endpoints:['/v1/treasury/financial_accounts','/v1/treasury/credit_reversals','/v1/treasury/debit_reversals','/v1/treasury/transactions'],docs_url:'https://stripe.com/docs/treasury',tags:['banking','treasury','payments','fintech'],favorite:false},
  {name:'Plaid Transactions',category:'finance',description:'Extended Plaid API for detailed transaction categorization, enrichment, and insights.',auth:'OAuth 2.0',rate_limit:'1000 req/hour',endpoints:['/transactions/get','/transactions/sync','/categories/get','/transactions/enrich'],docs_url:'https://plaid.com/docs/api/',tags:['banking','transactions','enrichment','categorization'],favorite:false},
  {name:'Bluesky',category:'social',description:'Decentralized social media protocol API for posting, reading, and interacting with content on the AT Protocol.',auth:'Bearer Token',rate_limit:'300 req/min',endpoints:['/xrpc/app.bsky.feed.getTimeline','/xrpc/app.bsky.feed.getPosts','/xrpc/app.bsky.graph.getFollows','/xrpc/app.bsky.actor.getProfile'],docs_url:'https://docs.bsky.app/',tags:['decentralized','social-media','at-protocol','microblogging'],favorite:false},
  {name:'Threads',category:'social',description:"Meta's text-based social media platform API for accessing posts, user profiles, and replies.",auth:'Bearer Token',rate_limit:'200 req/hour',endpoints:['/v1/threads','/v1/users','/v1/search','/v1/replies'],docs_url:'https://developers.facebook.com/docs/threads-api',tags:['social-media','text','meta','conversation'],favorite:false},
  {name:'Gab',category:'social',description:'Decentralized social network API for posts, user profiles, and federated timeline access.',auth:'Bearer Token',rate_limit:'100 req/min',endpoints:['/api/v1/timelines/public','/api/v1/posts','/api/v1/accounts','/api/v1/search'],docs_url:'https://docs.gab.com/',tags:['decentralized','social-media','free-speech','federation'],favorite:false},
  {name:'MeWe',category:'social',description:'Privacy-focused social media platform API for accessing posts, groups, and user data.',auth:'OAuth 2.0',rate_limit:'100 req/hour',endpoints:['/api/v1/posts','/api/v1/users','/api/v1/groups','/api/v1/messages'],docs_url:'https://mewe.com/developers',tags:['social-media','privacy','groups','messaging'],favorite:false},
  {name:'Weatherbit',category:'weather',description:'Weather API providing current conditions, forecasts, historical data, and air quality indices.',auth:'API Key',rate_limit:'1000 calls/day',endpoints:['/v2.0/current','/v2.0/forecast/daily','/v2.0/history/daily','/v2.0/airquality'],docs_url:'https://www.weatherbit.io/api',tags:['weather','forecast','air-quality','historical'],favorite:false},
  {name:'Visual Crossing',category:'weather',description:'Weather data API providing forecasts, historical weather, and climate data with GIS integration.',auth:'API Key',rate_limit:'1000 calls/day',endpoints:['/VisualCrossingWebServices/rest/services/timeline','/VisualCrossingWebServices/rest/services/weatherdata/forecast','/VisualCrossingWebServices/rest/services/weatherdata/history'],docs_url:'https://www.visualcrossing.com/resources/documentation/weather-api/',tags:['weather','forecast','historical','gis'],favorite:false},
  {name:'Meteostat',category:'weather',description:'Open weather data API providing historical weather records, climate normals, and station data.',auth:'None',rate_limit:'10000 requests/month',endpoints:['/v2/weather/daily','/v2/weather/hourly','/v2/stations','/v2/climate/normals'],docs_url:'https://dev.meteostat.net/',tags:['weather','historical','open-data','climate'],favorite:false},
  {name:'Esri ArcGIS',category:'maps',description:'Enterprise mapping and GIS platform API for spatial analysis, mapping, and location services.',auth:'API Key',rate_limit:'1000 req/day',endpoints:['/arcgis/rest/services','/sharing/rest/search','/sharing/rest/content','/featureserver'],docs_url:'https://developers.arcgis.com/',tags:['maps','gis','spatial','enterprise'],favorite:false},
  {name:'Mapillary',category:'maps',description:'Street-level imagery API for accessing photos, map features, and computer vision data.',auth:'Bearer Token',rate_limit:'5000 req/day',endpoints:['/v1/map_features','/v1/sequences','/v1/images','/v1/search'],docs_url:'https://www.mapillary.com/developers/api-documentation',tags:['maps','street-view','imagery','computer-vision'],favorite:false},
  {name:'Resend',category:'email',description:'Modern email delivery API for transactional and marketing emails with excellent deliverability.',auth:'Bearer Token',rate_limit:'100 emails/sec',endpoints:['/v1/emails','/v1/domains','/v1/suppressions','/v1/templates'],docs_url:'https://resend.com/docs',tags:['email','delivery','transactional','api-first'],favorite:false},
  {name:'Amazon MWS',category:'ecommerce',description:'Amazon Marketplace Web Service API for managing orders, inventory, pricing, and reports.',auth:'AWS Signature',rate_limit:'10 req/sec',endpoints:['/Orders/2013-09-01','/Products/2011-10-01','/FulfillmentInventory/2010-10-01','/Reports/2009-01-01'],docs_url:'https://developer.amazonservices.com/',tags:['ecommerce','amazon','marketplace','orders'],favorite:false},
  {name:'eBay',category:'ecommerce',description:'eBay marketplace API for managing listings, orders, buyers, and seller analytics.',auth:'OAuth 2.0',rate_limit:'5000 calls/day',endpoints:['/sell/inventory/v1','/sell/account/v1','/sell/fulfillment/v1','/buy/browse/v1'],docs_url:'https://developer.ebay.com/api-docs',tags:['ecommerce','marketplace','auctions','orders'],favorite:false},
  {name:'Bitbucket',category:'developer',description:"Atlassian's Git repository management API for code collaboration, pull requests, and pipelines.",auth:'OAuth 2.0',rate_limit:'1000 req/hour',endpoints:['/2.0/repositories','/2.0/pullrequests','/2.0/workspaces','/2.0/pipelines'],docs_url:'https://developer.atlassian.com/bitbucket/api',tags:['git','repositories','ci-cd','collaboration'],favorite:false},
  {name:'FDA',category:'health',description:'U.S. Food and Drug Administration API for drug information, food safety, and medical device data.',auth:'API Key',rate_limit:'1000 req/day',endpoints:['/drug/label.json','/drug/enforcement.json','/food/enforcement.json','/device/510k.json'],docs_url:'https://open.fda.gov/apis/',tags:['health','government','drugs','food-safety','medical-devices'],favorite:false},
  {name:'NIH',category:'health',description:'National Institutes of Health API for accessing medical research data, clinical trials, and health statistics.',auth:'None',rate_limit:'10 req/sec',endpoints:['/v2/studies','/v2/drugs','/v2/diseases','/v2/gene'],docs_url:'https://api.ncbi.nlm.nih.gov/',tags:['health','research','medical','clinical-trials','government'],favorite:false},
  {name:'OpenFDA',category:'health',description:'Open FDA API providing access to FDA datasets on drugs, devices, food, and adverse events.',auth:'None',rate_limit:'1000 req/day',endpoints:['/drug/label.json','/drug/event.json','/device/event.json','/food/enforcement.json'],docs_url:'https://open.fda.gov/apis/',tags:['health','fda','open-data','adverse-events'],favorite:false},
  {name:'Discogs',category:'music',description:'Music database and marketplace API for accessing discography data, releases, and artist information.',auth:'OAuth 2.0',rate_limit:'5000 req/day',endpoints:['/database/search','/database/release','/artists/{id}','/masters/{id}'],docs_url:'https://www.discogs.com/developers',tags:['music','database','discography','marketplace'],favorite:false},
  {name:'Shazam',category:'music',description:'Music recognition and discovery API for identifying songs, accessing lyrics, and chart data.',auth:'API Key',rate_limit:'5000 req/day',endpoints:['/v1/search','/v1/songs/{id}','/v1/artists/{id}','/v1/charts'],docs_url:'https://developer.shazam.com/',tags:['music','recognition','discovery','lyrics'],favorite:false},
  {name:'iTunes Search',category:'music',description:'Apple iTunes Store API for searching music, podcasts, audiobooks, and media content.',auth:'None',rate_limit:'200 req/min',endpoints:['/search','/lookup','/reviews','/rss'],docs_url:'https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/iTuneSearchAPI/',tags:['music','apple','search','itunes'],favorite:false},
  {name:'Vimeo OTT',category:'video',description:'Vimeo OTT platform API for video streaming, channel management, and content delivery.',auth:'Bearer Token',rate_limit:'5000 req/hour',endpoints:['/videos','/channels','/albums','/users'],docs_url:'https://developer.vimeo.com/api/ott',tags:['video','ott','streaming','channels'],favorite:false},
  {name:'Dailymotion',category:'video',description:'Dailymotion video platform API for videos, channels, playlists, and analytics.',auth:'OAuth 2.0',rate_limit:'1000 req/hour',endpoints:['/videos','/channels','/playlists','/search'],docs_url:'https://developers.dailymotion.com/',tags:['video','streaming','platform','analytics'],favorite:false},
  {name:'AP News',category:'news',description:'Associated Press news API for real-time news coverage from global sources.',auth:'API Key',rate_limit:'500 req/day',endpoints:['/v2/search','/v2/top-stories','/v2/sources','/v2/collections'],docs_url:'https://developer.ap.org/',tags:['news','ap','wire-service','global'],favorite:false},
  {name:'Reuters',category:'news',description:'Reuters news API for financial and general news coverage from a global news organization.',auth:'API Key',rate_limit:'1000 req/day',endpoints:['/v1/news','/v1/topics','/v1/sources','/v1/search'],docs_url:'https://developers.reuters.com/',tags:['news','reuters','financial','global'],favorite:false},
  {name:'Bloomberg',category:'news',description:'Bloomberg terminal API for financial news, market data, and analytics.',auth:'API Key',rate_limit:'100 req/day',endpoints:['/v1/news','/v1/markets','/v1/companies','/v1/analytics'],docs_url:'https://www.bloomberg.com/professional/support/api-library/',tags:['news','financial','bloomberg','markets'],favorite:false},
  {name:'ESPN Fantasy',category:'sports',description:'ESPN Fantasy Sports API for managing fantasy leagues, rosters, and scoring.',auth:'API Key',rate_limit:'100 req/min',endpoints:['/v3/fantasy/leagues','/v3/fantasy/teams','/v3/fantasy/rosters','/v3/fantasy/scoring'],docs_url:'https://developer.espn.com/apis',tags:['sports','fantasy','leagues','rosters'],favorite:false},
  {name:'FiveThirtyEight',category:'sports',description:'Sports analytics and prediction API for sports statistics, predictions, and probability models.',auth:'API Key',rate_limit:'100 req/day',endpoints:['/v1/predictions','/v1/statistics','/v1/teams','/v1/games'],docs_url:'https://github.com/fivethirtyeight/data',tags:['sports','analytics','predictions','statistics'],favorite:false},
  {name:'S3 Compatible',category:'storage',description:'S3-compatible object storage API for cloud storage services with AWS S3 API compatibility.',auth:'Access Key',rate_limit:'Unlimited',endpoints:['/bucket','/object','/bucket-policy','/lifecycle'],docs_url:'https://docs.aws.amazon.com/AmazonS3/latest/API/',tags:['storage','s3','cloud','compatible'],favorite:false},
  {name:'Cloudflare R2',category:'storage',description:'Cloudflare R2 object storage API for S3-compatible cloud storage with no egress fees.',auth:'API Key',rate_limit:'Unlimited',endpoints:['/v1/buckets','/v1/objects','/v1/upload','/v1/download'],docs_url:'https://developers.cloudflare.com/r2/',tags:['storage','cloudflare','s3-compatible','cdn'],favorite:false},
  {name:'DigitalOcean',category:'storage',description:'DigitalOcean cloud platform API for object storage (Spaces), compute, and networking.',auth:'OAuth 2.0',rate_limit:'5000 req/hour',endpoints:['/v2/spaces','/v2/droplets','/v2/networking','/v2/volumes'],docs_url:'https://docs.digitalocean.com/',tags:['cloud','digitalocean','storage','compute'],favorite:false},
  {name:'Linode',category:'storage',description:'Linode cloud platform API for object storage, compute instances, and networking.',auth:'Bearer Token',rate_limit:'300 req/min',endpoints:['/v4/object-storage','/v4/linode/instances','/v4/networking','/v4/volumes'],docs_url:'https://www.linode.com/docs/api/',tags:['cloud','linode','storage','compute'],favorite:false}
];

const toAdd = newEntries.filter(e => !existingNames.has(e.name));
console.log('New unique entries to add:', toAdd.length);
data.push(...toAdd);
fs.writeFileSync(path, JSON.stringify(data, null, 2) + '\n');
console.log('Total entries:', data.length);
